theme: jekyll-theme-minimal
title: Shao-Ying (Clare) Huang
description: I am a Ph.D candidate in the Department of the Geophysical Sciences in University of Chicago. This is my Github directory which includes all my project repositories with descriptions.
show_downloads: false
google_analytics:
